### ISSUE TITLE
Missing images for products from habitat.zip catalog (develop 9.0.1.9)

### ISSUE THREAD

**Issue by whuu** [Sitecore/Sitecore.HabitatHome.Commerce#27]
Product catalog from `/Sitecore.HabitatHome.Commerce/src/Project/HabitatHome/engine/wwwroot/data/Catalogs/Habitat.zip` is different than the default one from 9.0 Update-1 installation.

This causes issues with missing images for some products, because image items for them are not present in Sitecore.Commerce.Habitat.Images-1.0.0.zip. I couldn't find those missing images in serialization folders in repo either.

Example ID of different product: 6042293 (SellableItem20.json from your habitat.zip)
In your package it has 6 images:

```
"7c962248-9bee-4eb8-a8d3-3a2f4b6a8888", "d66905c2-ed08-4528-a288-12094e603acd", 
"fe89ebd8-a20b-4c30-a645-f5585bb086f8", "08de2e9e-244b-4570-a067-d63d3337c498", 
"3633a0d1-e0f9-4336-a17c-3519a968c7f2", "a4f49c7b-9ba8-428f-ae52-08e3903d72fa"
```

In default habitat.zip (and in Sitecore.Commerce.Habitat.Images-1.0.0.zip) the product has 4 images where only 2 IDs are same as in your package. After initializing catalg with habitat.zip from repo some of the product images are missing. It applies to several other products as well.

**Comment by jeanfrancoislarente** [comment]
I need to find a place to host the product images (150mb). I'm asking around for the best place and will resolve the issue when I get the answer.

**Comment by jeanfrancoislarente** [comment]
All images for Habitat Home Commerce are now on box: https://sitecore.box.com/shared/static/bjvge68eqge87su5vg258366rve6bg5d.zip
Thanks for reporting @whuu
