### ISSUE TITLE
Getting "The following tasks did not complete: initial. Did you forget to signal async completion?" exception

### ISSUE THREAD

**Issue by chorpo** [Sitecore/Sitecore.HabitatHome.Commerce#28]
**Describe the bug**
Running initial task from Task Runner Explorer from 9.0.2 branch is not working

**To Reproduce**
1. Go to 'Task Runner Explorer' in VS2017
2. Right Click on 'initial' task
3. Click Run
4. See this error:

The following tasks did not complete: initial
Did you forget to signal async completion?

**Expected behavior**
Task runs without any exceptions

**Comment by chorpo** [comment]
This issue was introduced by upgrading Gulp from version 3.x to 4.x. See more information here -> https://github.com/gulpjs/gulp/issues/1613

**Comment by jeanfrancoislarente** [comment]
Fixed by #29
