### ISSUE TITLE
Powershell script execution

### ISSUE THREAD

**Issue by amitabhdas86** [Sitecore/Sitecore.HabitatHome.Commerce#39]
**Describe the bug**
When executing _deploy-commerce-engine.ps1_ the PowerShell scripts gives an error as 

> ConvertFrom-Json : Unrecognized escape sequence.

@jeanfrancoislarente Kindly have a look this might be related to the Global.json changes added by you.

**To Reproduce**
1. Open the **deploy-commerce-engine.ps1** and modify the parameters as per your environment
2. Open PowerShell as Admin and browse to the path of **deploy-commerce-engine.ps1** inside HabitatHome.Commerce
3. Execute the command _.\deploy-commerce-engine.ps1 -Boostrap -Initialize_

**Expected behavior**
The deployment script should execute without any errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/42270577/43955449-21b00d04-9c55-11e8-853d-f4c259a107da.png)

**Demo Version**
https://github.com/Sitecore/Sitecore.HabitatHome.Commerce/tree/fa6154d213c098c8a64562bf550cbad288e66579

**Additional context**
This issue was not existing before and was due to the changes done on 09-Sep-2018

**Comment by jeanfrancoislarente** [comment]
@amitabhdas86 can you provide a diff between your .ps1 and the original?

You shouldn't have to open deploy-commerce-engine.ps1, you should be able to simply provide parameters to it.

I've been using it daily and haven't encountered that problem. I'm thinking something didn't copy properly to your publishPath or something similar?

**Comment by jeanfrancoislarente** [comment]
@amitabhdas86  - just checking in one more time if you can provide additional details before I close the issue.
Thanks!
