### ISSUE TITLE
Wishlist functionality does not work

### ISSUE THREAD

**Issue by ezlateva** [Sitecore/Sitecore.HabitatHome.Commerce#43]
Found a few issues with the wishlist functionality

- It is excluded from the gulp script when building
- It is referencing a OData.Client version 7.4.4, which throws an error on the site, since only 7.3.1 being pushed
- Javascript calls for 'add to wishlist' from the shopping cart view does not initialize properly, and throws a console error
- After getting it to build and initialize, when adding things to the wishlist, I can't see the product details in the wishlist view under 'my account'

Demo Version
Demo Version 9.0.2.1
XP Version Supported 9.0.2
SXA 1.7.1
DEF 2.0.1

**Comment by jeanfrancoislarente** [comment]
Thank you!
