### ISSUE TITLE
Offline Order Import doesn't associate to customer

### ISSUE THREAD

**Issue by ezlateva** [Sitecore/Sitecore.HabitatHome.Commerce#53]
When I import an offline order through the UploadOrder.aspx utility page, the order does not get associated to the customer, even though a customer with the same email is registered

**To Reproduce**
1. Register a customer
2. Upload order with the same email address
3. View customer details in BizFx

**Expected behavior**
Uploaded order should show up under customer's orders

**Demo Version**
Demo Version 9.0.2.1
XP Version Supported 9.0.2
SXA 1.7.1
DEF 2.0.1
XC Version Supported 9.0.2 (when installing Sitecore.Habitat.Commerce)

**Comment by jeanfrancoislarente** [comment]
Thanks!!
